/**
 * Pre-renders every route to static HTML.
 *
 * Runs automatically as part of `npm run build`. There is no server at runtime — this
 * turns the SPA into a folder of real HTML files that Apache/cPanel serves directly,
 * so the first paint no longer waits for React to boot, and crawlers get real markup
 * with the right per-route <title> and meta tags.
 *
 * It also emits .htaccess, sitemap.xml and robots.txt, because all three have to carry the
 * deploy base path and public URL — see BASE_PATH and SITE_URL below.
 */
import { mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const dist = path.join(root, 'dist');
const ssrDir = path.join(root, '.ssr');

const template = readFileSync(path.join(dist, 'index.html'), 'utf8');
// pathToFileURL: Windows absolute paths are not valid ESM specifiers on their own.
const {
  render,
  ROUTE_PATHS,
  BASE_URL,
  SITE_URL: APP_SITE_URL,
} = await import(pathToFileURL(path.join(ssrDir, 'entry-server.js')).href);

/** Always starts and ends with a slash, e.g. '/' or '/emerge/'. */
const BASE = BASE_URL.endsWith('/') ? BASE_URL : `${BASE_URL}/`;

/** Public origin, taken from the app's own config (override with VITE_SITE_URL). */
const SITE_URL = APP_SITE_URL.replace(/\/$/, '');

/** Absolute public URL for an app route. */
const publicUrl = (route) => `${SITE_URL}${BASE}${route === '/' ? '' : route.slice(1)}`;

// Route paths come from the app itself, so this can never drift from the router.
// '/404.html' is the branded not-found page, which Apache serves via ErrorDocument.
const ROUTES = [...Object.values(ROUTE_PATHS), '/404.html'];

for (const route of ROUTES) {
  const { html, head } = render(route === '/404.html' ? '/404' : route);

  let page = template.replace('<div id="root"></div>', `<div id="root">${html}</div>`);

  // Replace the static <title> and description with the route's own, then append the rest.
  page = page
    .replace(/<title>[\s\S]*?<\/title>\s*/, '')
    .replace(/<meta\s+name="description"[\s\S]*?\/>\s*/, '')
    .replace('</head>', `  ${head}\n  </head>`);

  // Write each route twice so it resolves however the host is configured:
  //   about.html        — served directly by the .htaccess "try .html" rewrite, no redirect
  //   about/index.html  — served by Apache's DirectoryIndex if that rewrite is unavailable
  const targets =
    route === '/'
      ? [path.join(dist, 'index.html')]
      : route === '/404.html'
        ? [path.join(dist, '404.html')]
        : [
            path.join(dist, `${route.slice(1)}.html`),
            path.join(dist, route.slice(1), 'index.html'),
          ];

  for (const target of targets) {
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, page, 'utf8');
  }
  console.log(`  ${route} -> ${targets.map((t) => path.relative(dist, t)).join(', ')}`);
}

/* ---------------------------------------------------------------- host files */

/** Writes a template from scripts/ into dist/, substituting the deploy base. */
const emitTemplate = (templateName, outputName) => {
  const contents = readFileSync(path.join(here, templateName), 'utf8').replaceAll('__BASE__', BASE);
  writeFileSync(path.join(dist, outputName), contents, 'utf8');
};

// .htaccess: RewriteBase, the .html rewrite target and ErrorDocument all need the base.
emitTemplate('htaccess.template', '.htaccess');

// The manifest's start_url and icon paths are root-relative and need it too. A copy has to
// stay in public/ as well — Vite only rewrites the <link rel="manifest"> href for a file it
// can resolve there — so this overwrites the copy Vite already emitted.
emitTemplate('site.webmanifest.template', 'site.webmanifest');

// sitemap.xml: absolute URLs only, and /blog is deliberately excluded.
const priority = { '/': '1.0', '/focus-areas': '0.9', '/about': '0.8', '/our-work': '0.8' };
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/prerender.mjs. /blog is excluded: the route does not exist
     while FEATURES.blog is false. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${Object.values(ROUTE_PATHS)
  .map(
    (route) => `  <url>
    <loc>${publicUrl(route)}</loc>
    <changefreq>monthly</changefreq>
    <priority>${priority[route] ?? '0.7'}</priority>
  </url>`,
  )
  .join('\n')}
</urlset>
`;
writeFileSync(path.join(dist, 'sitemap.xml'), sitemap, 'utf8');

writeFileSync(
  path.join(dist, 'robots.txt'),
  `User-agent: *\nAllow: ${BASE}\n\nSitemap: ${SITE_URL}${BASE}sitemap.xml\n`,
  'utf8',
);

console.log(
  `  .htaccess, site.webmanifest, sitemap.xml, robots.txt  (base ${BASE}, site ${SITE_URL})`,
);

rmSync(ssrDir, { recursive: true, force: true });
console.log(`Pre-rendered ${ROUTES.length} routes.`);
