import puppeteer from 'puppeteer-core';
const [url,width,out]=process.argv.slice(2);
const b=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:'new',args:['--no-sandbox']});
const p=await b.newPage();
await p.setViewport({width:Number(width),height:1000,deviceScaleFactor:2});
await p.goto(url,{waitUntil:'networkidle0'});
await p.evaluate(()=>document.querySelectorAll('.reveal').forEach(n=>n.classList.add('is-visible')));
await new Promise(r=>setTimeout(r,900));
const el=await p.$('section.bg-brand-900');
await el.screenshot({path:out});
await b.close();
